# eksctl create cluster --config-file=eks.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ###ZARF_VAR_CLUSTER_NAME###  
  region: us-west-1
  version: "1.21"
managedNodeGroups:
- instanceType: t3.small
  name: ###ZARF_VAR_CLUSTER_NAME###-ng
  minSize: 3
  maxSize: 6
  spot: true
